env:
  CACHIX_NAME: federicoschonborn
jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        run: |
          git clone --depth 1 https://codeberg.org/FedericoSchonborn/nur-packages $GITHUB_WORKSPACE
      - if: inputs.runs-on == 'ubuntu-latest' && !contains(fromJSON('["x86_64-linux"]'), inputs.system)
        name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@v13
        with:
          extra-conf: |
            nix-path = nixpkgs=channel:${{ inputs.channel }}
            system = ${{ inputs.system }}
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - if: contains(fromJSON('["x86_64-linux", "aarch64-linux"]'), inputs.system)
        name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_NAME }}
      - name: Show Nixpkgs version
        run: |
          nix eval --impure --raw --expr "(import <nixpkgs> {}).lib.version"
      - name: Check evaluation
        run: |
          nix eval --impure --json --expr "builtins.mapAttrs (name: value: value.meta or {}) (import ./. {})"
      - name: Build Nix packages
        run: |
          nix run nixpkgs#nix-build-uncached -- ci.nix -A cacheOutputs -build-flags "-L"
name: Build
"on":
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      runs-on:
        required: true
        type: string
      system:
        required: true
        type: string
