env:
  CACHIX_NAME: federicoschonborn
jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        run: |
          git clone --verbose --depth 1 https://codeberg.org/FedericoSchonborn/nur-packages "$GITHUB_WORKSPACE"
      - if: inputs.runner == 'ubuntu-22.04' && inputs.targetSystem != inputs.buildSystem
        name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@v13
        with:
          nix-package-url: https://releases.lix.systems/lix/lix-2.90.0/lix-2.90.0-${{ inputs.buildSystem }}.tar.xz
          source-url: https://install.lix.systems/lix/lix-installer-${{ inputs.buildSystem }}
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - if: contains(fromJSON('["x86_64-linux","aarch64-linux","i686-linux","x86_64-darwin","aarch64-darwin"]'), inputs.buildSystem)
        name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_NAME }}
      - name: Dry Build Nix packages
        run: |
          nix build --dry-run --print-build-logs --keep-going --no-link --impure --file ./ci.nix cacheOutputs --system "${{ inputs.targetSystem }}" --inputs-from . --override-input nixpkgs ${{ inputs.flakeInput }}
      - name: Build Nix packages
        run: |
          nix build --print-build-logs --keep-going --no-link --impure --file ./ci.nix cacheOutputs --system "${{ inputs.targetSystem }}" --inputs-from . --override-input nixpkgs ${{ inputs.flakeInput }}
name: Build
"on":
  workflow_call:
    inputs:
      buildSystem:
        required: true
        type: string
      channel:
        required: true
        type: string
      flakeInput:
        required: true
        type: string
      runner:
        required: true
        type: string
      targetSystem:
        required: true
        type: string
