env:
  NUR_REPO: federicoschonborn
jobs:
  build-nixos-24_05-aarch64-linux:
    name: NixOS 24.05 (Linux/aarch64)
    needs:
      - build-nixos-unstable-aarch64-linux
      - build-nixos-24_05-x86_64-linux
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      buildSystem: x86_64-linux
      channel: nixos-24.05
      flakeInput: nixos-stable
      runner: ubuntu-22.04
      targetSystem: aarch64-linux
  build-nixos-24_05-x86_64-linux:
    name: NixOS 24.05 (Linux/x86_64)
    needs:
      - build-nixos-unstable-x86_64-linux
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      buildSystem: x86_64-linux
      channel: nixos-24.05
      flakeInput: nixos-stable
      runner: ubuntu-22.04
      targetSystem: x86_64-linux
  build-nixos-unstable-aarch64-linux:
    name: NixOS Unstable (Linux/aarch64)
    needs:
      - build-nixpkgs-unstable-aarch64-linux
      - build-nixos-unstable-x86_64-linux
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      buildSystem: x86_64-linux
      channel: nixos-unstable
      flakeInput: nixos-unstable
      runner: ubuntu-22.04
      targetSystem: aarch64-linux
  build-nixos-unstable-x86_64-linux:
    name: NixOS Unstable (Linux/x86_64)
    needs:
      - build-nixpkgs-unstable-x86_64-linux
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      buildSystem: x86_64-linux
      channel: nixos-unstable
      flakeInput: nixos-unstable
      runner: ubuntu-22.04
      targetSystem: x86_64-linux
  build-nixpkgs-24_05-darwin-aarch64-darwin:
    name: Nixpkgs 24.05 (Darwin/aarch64)
    needs:
      - build-nixpkgs-unstable-aarch64-darwin
      - build-nixpkgs-24_05-darwin-x86_64-darwin
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      buildSystem: aarch64-darwin
      channel: nixpkgs-24.05-darwin
      flakeInput: nixpkgs-stable-darwin
      runner: macos-14
      targetSystem: aarch64-darwin
  build-nixpkgs-24_05-darwin-x86_64-darwin:
    name: Nixpkgs 24.05 (Darwin/x86_64)
    needs:
      - build-nixpkgs-unstable-x86_64-darwin
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      buildSystem: x86_64-darwin
      channel: nixpkgs-24.05-darwin
      flakeInput: nixpkgs-stable-darwin
      runner: macos-13
      targetSystem: x86_64-darwin
  build-nixpkgs-unstable-aarch64-darwin:
    name: Nixpkgs Unstable (Darwin/aarch64)
    needs:
      - build-nixpkgs-unstable-x86_64-darwin
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      buildSystem: aarch64-darwin
      channel: nixpkgs-unstable
      flakeInput: nixpkgs-unstable
      runner: macos-14
      targetSystem: aarch64-darwin
  build-nixpkgs-unstable-aarch64-linux:
    name: Nixpkgs Unstable (Linux/aarch64)
    needs:
      - build-nixpkgs-unstable-x86_64-linux
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      buildSystem: x86_64-linux
      channel: nixpkgs-unstable
      flakeInput: nixpkgs-unstable
      runner: ubuntu-22.04
      targetSystem: aarch64-linux
  build-nixpkgs-unstable-x86_64-darwin:
    name: Nixpkgs Unstable (Darwin/x86_64)
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      buildSystem: x86_64-darwin
      channel: nixpkgs-unstable
      flakeInput: nixpkgs-unstable
      runner: macos-13
      targetSystem: x86_64-darwin
  build-nixpkgs-unstable-x86_64-linux:
    name: Nixpkgs Unstable (Linux/x86_64)
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      buildSystem: x86_64-linux
      channel: nixpkgs-unstable
      flakeInput: nixpkgs-unstable
      runner: ubuntu-22.04
      targetSystem: x86_64-linux
name: Build and Populate Cache
"on":
  pull_request: {}
  push:
    branches:
      - main
  schedule:
    - cron: 55 3 * * *
  workflow_dispatch: {}
